import type {
  ChatMessage,
  ChatResponsePayload,
  TravelPlanResponse,
  TripPlanDay,
  TripPlanResult,
} from "@/types";
import { travelPlanResponseToTripPlanResult } from "@/lib/travelPlanConversion";

function looksAutoGeneratedDayShell(day: TripPlanDay): boolean {
  const summary = day.summary?.trim() || "";
  if (!summary) {
    return false;
  }
  return /為主。$|focuses on |starter itinerary|lighter route/u.test(summary);
}

function isPlaceholderDaySummary(summary: string | undefined): boolean {
  const normalized = summary?.trim() || "";
  if (!normalized) {
    return true;
  }
  return /^(?:尚未安排內容|未安排內容|尚無安排|暫未安排|pending)$/iu.test(normalized);
}

function shouldFillEmptyDayFromReplacement(day: TripPlanDay, replacement: TripPlanDay): boolean {
  if (day.items.length > 0 || replacement.items.length === 0) {
    return false;
  }
  if (looksAutoGeneratedDayShell(day) || isPlaceholderDaySummary(day.summary)) {
    return true;
  }

  const currentTheme = day.theme?.trim() || "";
  const replacementTheme = replacement.theme?.trim() || "";
  if (currentTheme && replacementTheme && currentTheme === replacementTheme) {
    return true;
  }

  return replacement.items.some((item) => {
    const title = item.title.trim();
    const locationName = item.location?.name?.trim() || "";
    return Boolean(currentTheme && (currentTheme === title || currentTheme === locationName));
  });
}

function mergeTripPlansPreferringNonEmptyDays(base: TripPlanResult, fallback: TripPlanResult): TripPlanResult {
  const baseByNumber = new Map(base.days.map((day) => [day.dayNumber, day]));
  const fallbackByNumber = new Map(fallback.days.map((day) => [day.dayNumber, day]));
  const allDayNumbers = [...new Set([...baseByNumber.keys(), ...fallbackByNumber.keys()])].sort(
    (left, right) => left - right,
  );

  return {
    ...base,
    days: allDayNumbers.map((dayNumber) => {
      const current = baseByNumber.get(dayNumber);
      const replacement = fallbackByNumber.get(dayNumber);
      if (!current) {
        return replacement!;
      }
      if (!replacement || !shouldFillEmptyDayFromReplacement(current, replacement)) {
        return current;
      }
      return {
        ...current,
        theme: current.theme || replacement.theme,
        summary: current.summary || replacement.summary,
        items: replacement.items,
      };
    }),
  };
}

export function countTripPlanItems(plan: TripPlanResult | null | undefined): number {
  if (!plan) {
    return 0;
  }
  return plan.days.reduce((total, day) => total + day.items.length, 0);
}

export function pickPreferredGeneratedTripPlan(
  response: Pick<ChatResponsePayload, "itinerarySuggestion" | "reply" | "tripProfile">,
): TripPlanResult | null {
  const structuredPlan = response.itinerarySuggestion ?? null;
  const replyTravelPlan = response.reply.travelPlan;
  const replyPlan = replyTravelPlan
    ? travelPlanResponseToTripPlanResult(replyTravelPlan, {
        targetDayCount:
          response.tripProfile?.duration_days && response.tripProfile.duration_days > 0
            ? response.tripProfile.duration_days
            : undefined,
      })
    : null;

  if (!structuredPlan) {
    return replyPlan;
  }
  if (!replyPlan) {
    return structuredPlan;
  }

  const mergedStructured = mergeTripPlansPreferringNonEmptyDays(structuredPlan, replyPlan);
  const mergedCount = countTripPlanItems(mergedStructured);
  const structuredCount = countTripPlanItems(structuredPlan);
  const replyCount = countTripPlanItems(replyPlan);

  if (mergedCount >= replyCount && mergedCount >= structuredCount) {
    return mergedStructured;
  }

  return replyCount > structuredCount ? replyPlan : structuredPlan;
}

export function repairSparseItineraryDaysFromTravelPlan(
  itinerary: TripPlanDay[],
  travelPlan: TravelPlanResponse,
  targetDayCount?: number,
): TripPlanDay[] | null {
  const recovered = travelPlanResponseToTripPlanResult(travelPlan, { targetDayCount });
  const next = mergeTripPlansPreferringNonEmptyDays(
    {
      summary: "",
      days: itinerary,
    },
    recovered,
  ).days;

  const changed = next.some((day, index) => day !== itinerary[index]);
  return changed ? next : null;
}

export function repairSparseItineraryFromLatestChatTravelPlan(
  itinerary: TripPlanDay[],
  messages: ChatMessage[],
  targetDayCount?: number,
): TripPlanDay[] | null {
  const latestTravelPlan = [...messages]
    .reverse()
    .find((message) => message.responseType === "travel_plan" && message.travelPlan);
  if (!latestTravelPlan?.travelPlan) {
    return null;
  }
  return repairSparseItineraryDaysFromTravelPlan(itinerary, latestTravelPlan.travelPlan, targetDayCount);
}
