import type { ChatResponsePayload, TravelPlanResponse, TripPlanDay, TripPlanResult } from "@/types";
import { travelPlanResponseToTripPlanResult } from "@/lib/travelPlanConversion";

function looksAutoGeneratedDayShell(day: TripPlanDay): boolean {
  const summary = day.summary?.trim() || "";
  if (!summary) {
    return false;
  }
  return /為主。$|focuses on |starter itinerary|lighter route/u.test(summary);
}

export function countTripPlanItems(plan: TripPlanResult | null | undefined): number {
  if (!plan) {
    return 0;
  }
  return plan.days.reduce((total, day) => total + day.items.length, 0);
}

export function pickPreferredGeneratedTripPlan(
  response: Pick<ChatResponsePayload, "itinerarySuggestion" | "reply" | "tripProfile">,
): TripPlanResult | null {
  const structuredPlan = response.itinerarySuggestion ?? null;
  const replyTravelPlan = response.reply.travelPlan;
  const replyPlan = replyTravelPlan
    ? travelPlanResponseToTripPlanResult(replyTravelPlan, {
        targetDayCount:
          response.tripProfile?.duration_days && response.tripProfile.duration_days > 0
            ? response.tripProfile.duration_days
            : undefined,
      })
    : null;

  if (!structuredPlan) {
    return replyPlan;
  }
  if (!replyPlan) {
    return structuredPlan;
  }

  return countTripPlanItems(replyPlan) > countTripPlanItems(structuredPlan)
    ? replyPlan
    : structuredPlan;
}

export function repairSparseItineraryDaysFromTravelPlan(
  itinerary: TripPlanDay[],
  travelPlan: TravelPlanResponse,
  targetDayCount?: number,
): TripPlanDay[] | null {
  const recovered = travelPlanResponseToTripPlanResult(travelPlan, { targetDayCount });
  let changed = false;

  const next = itinerary.map((day) => {
    const replacement = recovered.days.find((candidate) => candidate.dayNumber === day.dayNumber);
    if (
      !replacement ||
      day.items.length > 0 ||
      replacement.items.length === 0 ||
      !looksAutoGeneratedDayShell(day)
    ) {
      return day;
    }
    changed = true;
    return {
      ...day,
      theme: day.theme || replacement.theme,
      summary: day.summary || replacement.summary,
      items: replacement.items,
    };
  });

  return changed ? next : null;
}
